spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  datasource:
    url: ${mysql-url}
    driver-class-name: ${mysql-driver-class-name}
    username: ${mysql-username}
    password: ${mysql-password}
  data:
    redis:
      host: ${redis-host}
      port: ${redis-port}
      password: ${redis-password}
      database: ${redis-db-api}

jwt:
  secret: ${jwt-secret}
  access-duration: ${jwt-access-duration}
  refresh-duration: ${jwt-refresh-duration}

oauth:
  kakao:
    client-id: ${kakao-client-id}
    client-secret: ${kakao-client-secret}
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"
    redirect-uri: "${kakao-redirect-uri}"
    grant-type: authorization_code

aws:
  access-key: ${aws-access-key}
  secret-key: ${aws-secret-key}
  region: ${aws-region}
  s3:
    bucket-name: ${aws-s3-bucket-name}

front-domain: ${front-domain}

# 프로덕션 로깅 레벨: info
logging:
  level:
    root: info